### ISSUE TITLE
Virtual environment?

### ISSUE THREAD

**Issue by final48923** [rashdanml/twitch-recorder#2]
I get this error message: 

04h56m21s   ****** online. Stream recording in session, using OAuth_Token:  *****
Traceback (most recent call last):
  File "/home/twitch/twitch-recorder/twitch-recorder.py", line 179, in <module>
    main(sys.argv[1:])
  File "/home/twitch/twitch-recorder/twitch-recorder.py", line 175, in main
    twitch_recorder.run()
  File "/home/twitch/twitch-recorder/twitch-recorder.py", line 154, in run
    self.loopcheck()
  File "/home/twitch/twitch-recorder/twitch-recorder.py", line 97, in loopcheck
    subprocess.call(["venv/bin/streamlink", "--twitch-disable-hosting", "--twitch-disable-ads",
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'venv/bin/streamlink'"

I don't know how to solve this, can anyone help me out?

**Comment by rashdanml** [comment]
> 

Create a virtual environment using whatever preferred method, and install streamlink in that virtual environment. When you run the script, make sure to run it from within the virtual environment. 

Alternatively, if you don't want to use virtual environments, change ```venv/bin/streamlink``` to just ```streamlink```
